version: '3'

services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - "8123:8123"
    volumes:
      - /var/lib/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
